---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cryostat
  namespace: cryostat
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: cryostat
            port:
              number: 8181
